package by.epam.web.unit6.command;

public enum CommandName {
    AUTHORIZATION, NO_SUCH_COMMAND, EDIT_PROFILE, REGISTRATION, CREATE_USER, UPDATE_USER, LOGOUT,
    SHOW_TARIFS, UPDATE_BALANCE, SHOW_USERS, ADD_NOTE, DELETE_NOTE, CHANGE_STATUS, CHANGE_BALANCE,
    DELETE_USER, DELETE_TARIF, EDIT_TARIF, ADD_TARIF, SHOW_USER_TARIF, LOCAL
}
